### ISSUE TITLE
incorrect dependency type

### ISSUE THREAD

**Issue by chorny** [kablamo/p5-shell-carapace#5]
Minilla is listed as 'build' dependency in cpanfile. If it is not used in module installation, it should be listed as 'develop'. See https://metacpan.org/pod/CPAN::Meta::Spec#Phases

**Comment by kablamo** [comment]
Thanks!  Fixed: https://github.com/kablamo/p5-shell-carapace/commit/b54e2c691983ac53aae3e399bca82bc097626474
